ARG APP_TYPE=node

FROM node:18-alpine AS base_node
WORKDIR /app
COPY node/ .
RUN npm install


FROM python:3.10-alpine AS base_python
WORKDIR /app
COPY python/ .
RUN pip install -r requirements.txt

FROM base_${APP_TYPE}

ARG APP_TYPE
ENV APP_TYPE=$APP_TYPE

WORKDIR /app

CMD ["sh", "-c", "if [ \"$APP_TYPE\" = \"node\" ]; then node index.js; else python app.py; fi"]